In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/sunnysavita10/credit_card_pw_hindi/main/creditCardFraud_28011964_120214.csv")

In [4]:
df.head()

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0      50000    1          2         1   57     -1      0     -1      0   
1      50000    1          1         2   37      0      0      0      0   
2     500000    1          1         2   29      0      0      0      0   
3     100000    2          2         2   23      0     -1     -1      0   
4     140000    2          3         1   28      0      0      2      0   

   PAY_5  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0      0  ...      20940      19146      19131      2000     36681     10000   
1      0  ...      19394      19619      20024      2500      1815       657   
2      0  ...     542653     483003     473944     55000     40000     38000   
3      0  ...        221       -159        567       380       601         0   
4      0  ...      12211      11793       3719      3329         0       432   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0      9000       689       679                           0  
1      1000      1000       800                           0  
2     20239     13750     13770                           0  
3       581      1687      1542                           0  
4      1000      1000      1000                           0  

[5 rows x 24 columns]

In [5]:
df.shape

(1001, 24)

In [6]:
df['default payment next month'].unique()

array([0, 1])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   LIMIT_BAL                   1001 non-null   int64
 1   SEX                         1001 non-null   int64
 2   EDUCATION                   1001 non-null   int64
 3   MARRIAGE                    1001 non-null   int64
 4   AGE                         1001 non-null   int64
 5   PAY_0                       1001 non-null   int64
 6   PAY_2                       1001 non-null   int64
 7   PAY_3                       1001 non-null   int64
 8   PAY_4                       1001 non-null   int64
 9   PAY_5                       1001 non-null   int64
 10  PAY_6                       1001 non-null   int64
 11  BILL_AMT1                   1001 non-null   int64
 12  BILL_AMT2                   1001 non-null   int64
 13  BILL_AMT3                   1001 non-null   int64
 14  BILL_AMT

In [8]:
df.isnull().sum()

LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default payment next month    0
dtype: int64

In [9]:
x = df.drop('default payment next month',axis=1)

In [10]:
y = df['default payment next month']

In [11]:
x

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0         50000    1          2         1   57     -1      0     -1      0   
1         50000    1          1         2   37      0      0      0      0   
2        500000    1          1         2   29      0      0      0      0   
3        100000    2          2         2   23      0     -1     -1      0   
4        140000    2          3         1   28      0      0      2      0   
...         ...  ...        ...       ...  ...    ...    ...    ...    ...   
996      100000    1          2         1   29      0      0      0      0   
997      200000    2          2         1   28      0      0      0      0   
998       90000    2          2         1   40     -1     -1     -1     -1   
999      360000    1          1         2   36      1     -2     -2     -2   
1000     150000    2          3         2   30     -2     -2     -2     -2   

      PAY_5  ...  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
0         0  ...      35835      20940      19146      19131      2000   
1         0  ...      57608      19394      19619      20024      2500   
2         0  ...     445007     542653     483003     473944     55000   
3         0  ...        601        221       -159        567       380   
4         0  ...      12108      12211      11793       3719      3329   
...     ...  ...        ...        ...        ...        ...       ...   
996      -1  ...      67782      -2618      95748     101299      3320   
997       0  ...       8441      97041     103541       3632      5000   
998      -1  ...       1114        657       1332        780         0   
999      -2  ...          0          0          0          0         0   
1000     -2  ...       3420       2527          0          0      9664   

      PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  
0        36681     10000      9000       689       679  
1         1815       657      1000      1000       800  
2        40000     38000     20239     13750     13770  
3          601         0       581      1687      1542  
4            0       432      1000      1000      1000  
...        ...       ...       ...       ...       ...  
996       5000         0    100000      7186         0  
997       2000     89000      6500        91      1504  
998       2806      2256      2274       780         0  
999          0         0         0         0         0  
1000      3420      2612         0         0         0  

[1001 rows x 23 columns]

In [12]:
y

0       0
1       0
2       0
3       0
4       0
       ..
996     0
997     0
998     0
999     1
1000    1
Name: default payment next month, Length: 1001, dtype: int64

In [13]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=69)

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [17]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [18]:
x_train.max()

np.float64(19.962575988354352)

In [19]:
x_train.min()

np.float64(-6.011583587684485)

In [20]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()

In [21]:
nb.fit(x_train,y_train)

GaussianNB()

In [22]:
y_predicted = nb.predict(x_test)

In [23]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [24]:
print(accuracy_score(y_test,y_predicted)*100)
print(confusion_matrix(y_test,y_predicted))
print(classification_report(y_test,y_predicted))

71.64179104477611
[[121  35]
 [ 22  23]]
              precision    recall  f1-score   support

           0       0.85      0.78      0.81       156
           1       0.40      0.51      0.45        45

    accuracy                           0.72       201
   macro avg       0.62      0.64      0.63       201
weighted avg       0.75      0.72      0.73       201



In [25]:
from sklearn.model_selection import GridSearchCV

In [26]:
from sklearn.naive_bayes import GaussianNB
new_nb = GaussianNB()

In [27]:
grid = {'var_smoothing' : [1e-9,0.1, 0.001, 0.5,0.05,0.01,1e-8,1e-7,1e-6,1e-10,1e-11]}

In [28]:
gs = GridSearchCV(new_nb,param_grid=grid,cv=5,verbose=3)

In [29]:
gs.fit(x_train,y_train)

Fitting 5 folds for each of 11 candidates, totalling 55 fits
[CV 1/5] END ...............var_smoothing=1e-09;, score=0.738 total time=   0.0s
[CV 2/5] END ...............var_smoothing=1e-09;, score=0.750 total time=   0.0s
[CV 3/5] END ...............var_smoothing=1e-09;, score=0.406 total time=   0.0s
[CV 4/5] END ...............var_smoothing=1e-09;, score=0.713 total time=   0.0s
[CV 5/5] END ...............var_smoothing=1e-09;, score=0.688 total time=   0.0s
[CV 1/5] END .................var_smoothing=0.1;, score=0.750 total time=   0.0s
[CV 2/5] END .................var_smoothing=0.1;, score=0.750 total time=   0.0s
[CV 3/5] END .................var_smoothing=0.1;, score=0.469 total time=   0.0s
[CV 4/5] END .................var_smoothing=0.1;, score=0.744 total time=   0.0s
[CV 5/5] END .................var_smoothing=0.1;, score=0.706 total time=   0.0s
[CV 1/5] END ...............var_smoothing=0.001;, score=0.738 total time=   0.0s
[CV 2/5] END ...............var_smoothing=0.001;

GridSearchCV(cv=5, estimator=GaussianNB(),
             param_grid={'var_smoothing': [1e-09, 0.1, 0.001, 0.5, 0.05, 0.01,
                                           1e-08, 1e-07, 1e-06, 1e-10, 1e-11]},
             verbose=3)

In [30]:
gs.best_params_

{'var_smoothing': 0.5}

In [31]:
y_predicted_new = gs.predict(x_test)

In [32]:
print(accuracy_score(y_test,y_predicted_new)*100)
print(confusion_matrix(y_test,y_predicted_new))
print(classification_report(y_test,y_predicted_new))

77.61194029850746
[[137  19]
 [ 26  19]]
              precision    recall  f1-score   support

           0       0.84      0.88      0.86       156
           1       0.50      0.42      0.46        45

    accuracy                           0.78       201
   macro avg       0.67      0.65      0.66       201
weighted avg       0.76      0.78      0.77       201



In [33]:
from sklearn.svm import SVC
svc = SVC()

In [34]:
grid = {'C':[0.1,0.5,1,10,100],
        'kernel':['linear', 'poly', 'rbf', 'sigmoid'],
        'gamma':['scale','auto']}

In [35]:
svc_gs = GridSearchCV(svc,param_grid=grid,verbose=3)

In [36]:
svc_gs.fit(x_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits
[CV 1/5] END .C=0.1, gamma=scale, kernel=linear;, score=0.794 total time=   0.0s
[CV 2/5] END .C=0.1, gamma=scale, kernel=linear;, score=0.787 total time=   0.0s
[CV 3/5] END .C=0.1, gamma=scale, kernel=linear;, score=0.787 total time=   0.0s
[CV 4/5] END .C=0.1, gamma=scale, kernel=linear;, score=0.787 total time=   0.0s
[CV 5/5] END .C=0.1, gamma=scale, kernel=linear;, score=0.787 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=scale, kernel=poly;, score=0.794 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=scale, kernel=poly;, score=0.794 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=scale, kernel=poly;, score=0.794 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=scale, kernel=poly;, score=0.781 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=scale, kernel=poly;, score=0.800 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=scale, kernel=rbf;, score=0.794 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=scale, kernel=rbf

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 0.5, 1, 10, 100],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             verbose=3)

In [37]:
svc_gs.best_params_

{'C': 0.1, 'gamma': 'auto', 'kernel': 'poly'}

In [38]:
y_predicted_svc = svc_gs.predict(x_test)

In [39]:
print(accuracy_score(y_test,y_predicted_svc)*100)
print(confusion_matrix(y_test,y_predicted_svc))
print(classification_report(y_test,y_predicted_svc))

76.61691542288557
[[153   3]
 [ 44   1]]
              precision    recall  f1-score   support

           0       0.78      0.98      0.87       156
           1       0.25      0.02      0.04        45

    accuracy                           0.77       201
   macro avg       0.51      0.50      0.45       201
weighted avg       0.66      0.77      0.68       201



In [42]:
from sklearn.naive_bayes import GaussianNB
opt_NB = GaussianNB(var_smoothing = 0.5)
opt_NB.fit(x_train,y_train)
y_predicted_optNB = opt_NB.predict(x_test)

In [43]:
print(accuracy_score(y_test,y_predicted_optNB)*100)
print(confusion_matrix(y_test,y_predicted_optNB))
print(classification_report(y_test,y_predicted_optNB))

77.61194029850746
[[137  19]
 [ 26  19]]
              precision    recall  f1-score   support

           0       0.84      0.88      0.86       156
           1       0.50      0.42      0.46        45

    accuracy                           0.78       201
   macro avg       0.67      0.65      0.66       201
weighted avg       0.76      0.78      0.77       201



In [46]:
import pickle
file = open('STD_Scaler.pkl','wb')
pickle.dump(scaler,file)
file.close()

In [47]:
file = open('GaussianNB.pkl','wb')
pickle.dump(opt_NB,file)
file.close()